//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DockerForm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DockerForm.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderbolt Switch is running in the background..
        /// </summary>
        internal static string BackgroundRun {
            get {
                return ResourceManager.GetString("BackgroundRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database sync conflict.
        /// </summary>
        internal static string DatabasConflictTitle {
            get {
                return ResourceManager.GetString("DatabasConflictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in your current database..
        /// </summary>
        internal static string DatabaseAlreadyExist {
            get {
                return ResourceManager.GetString("DatabaseAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} database sync conflict detected for {1}..
        /// </summary>
        internal static string DatabaseConflict {
            get {
                return ResourceManager.GetString("DatabaseConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings has been created..
        /// </summary>
        internal static string DatabaseCreate {
            get {
                return ResourceManager.GetString("DatabaseCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] database updated for {3} [{1}] [{2}].
        /// </summary>
        internal static string DatabaseFileUpdate {
            get {
                return ResourceManager.GetString("DatabaseFileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} CRC missmatch detected for {1}..
        /// </summary>
        internal static string DatabaseMissmatch {
            get {
                return ResourceManager.GetString("DatabaseMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings have been removed..
        /// </summary>
        internal static string DatabaseRemove {
            get {
                return ResourceManager.GetString("DatabaseRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] settings disabled for {3} [{1}] [{2}].
        /// </summary>
        internal static string DatabaseSettingsDisabled {
            get {
                return ResourceManager.GetString("DatabaseSettingsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] settings update skipped for {3} [{1}] [{2}].
        /// </summary>
        internal static string DatabaseSettingsSkipped {
            get {
                return ResourceManager.GetString("DatabaseSettingsSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] settings updated for {3} [{1}] [{2}].
        /// </summary>
        internal static string DatabaseSettingsUpdate {
            get {
                return ResourceManager.GetString("DatabaseSettingsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} settings have been updated..
        /// </summary>
        internal static string DatabaseUpdate {
            get {
                return ResourceManager.GetString("DatabaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU detected: {0} ({1}).
        /// </summary>
        internal static string DetectionCPU {
            get {
                return ResourceManager.GetString("DetectionCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device [{0}] has been disable..
        /// </summary>
        internal static string DeviceDisable {
            get {
                return ResourceManager.GetString("DeviceDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device [{0}] has been enabled..
        /// </summary>
        internal static string DeviceEnable {
            get {
                return ResourceManager.GetString("DeviceEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] has no settings defined..
        /// </summary>
        internal static string ErrorNoSettings {
            get {
                return ResourceManager.GetString("ErrorNoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] has an unreachable executable..
        /// </summary>
        internal static string ErrorUnreachableExe {
            get {
                return ResourceManager.GetString("ErrorUnreachableExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] has an unreachable folder..
        /// </summary>
        internal static string ErrorUnreachableFolder {
            get {
                return ResourceManager.GetString("ErrorUnreachableFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power profile{0}: {1}, applied..
        /// </summary>
        internal static string PowerProfileApplied {
            get {
                return ResourceManager.GetString("PowerProfileApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string PowerProfileDefault {
            get {
                return ResourceManager.GetString("PowerProfileDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power status: {0}.
        /// </summary>
        internal static string PowerStatus {
            get {
                return ResourceManager.GetString("PowerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler: {0} created..
        /// </summary>
        internal static string SchedulerCreate {
            get {
                return ResourceManager.GetString("SchedulerCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler: {0} disabled..
        /// </summary>
        internal static string SchedulerDisable {
            get {
                return ResourceManager.GetString("SchedulerDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler: {0} enabled..
        /// </summary>
        internal static string SchedulerEnable {
            get {
                return ResourceManager.GetString("SchedulerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been detected..
        /// </summary>
        internal static string VideoControllerDetected {
            get {
                return ResourceManager.GetString("VideoControllerDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has been disposed..
        /// </summary>
        internal static string WatcherDispose {
            get {
                return ResourceManager.GetString("WatcherDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has been created..
        /// </summary>
        internal static string WatcherStart {
            get {
                return ResourceManager.GetString("WatcherStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has stopped..
        /// </summary>
        internal static string WatcherStop {
            get {
                return ResourceManager.GetString("WatcherStop", resourceCulture);
            }
        }
    }
}
